theme: jekyll-theme-minimal
title: Laura W. Dozal
subtitle: iSchool PhD Student at the University of Arizona, 4th year
Description: Computational Social Scientist Specializing in information behavior and visual analysis.

plugins:
  - jekyll-image-size
